baseURL = 'https://theZFJ.github.io/'
languageCode = 'en-us'
title = "The Zombie Fridge Journal"
theme = 'mainroad'
paginate = '10'
publishDir = "docs"
googleAnalytics = "G-506M1GBBP6"

[Params]
  title = "The Zombie Fridge Journal"
  description = "Student-run newspaper reporting on general affairs and based in the NYC metropolitan area." # Site description. Used in meta description
  copyright = "The Zombie Fridge Journal" # Footer copyright holder, otherwise will use site title
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  opengraph = true
  mainSections = ["Africa", "Americas", "Asia-Pacific", "Business", "Domestic-Affairs", "Entertainment",
    "Europe", "Foreign-Affairs", "Medicine", "Middle-East", "Russia", "Science-and-Technology", 
    "Sports"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "15:04 2006-01-02" # Change the format of dates
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["custom.css"]

[Params.style.vars]
  highlightColor = "#e00007" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "zfjLogo.png" # Logo image. Path relative to "static"
  title = "The Zombie Fridge Journal" # Logo title, otherwise will use site title
  subtitle = "Semper serius." # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "social", "languages"]

[taxonomies]
  tag = "tags"
  category = "categories"
  staff = "staff"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "AkiraRorschach"
  instagram = "zfjnews"
  email = "alvin.wu@zfjnews.com"

  [markup]
  defaultMarkdownHandler = 'goldmark'
    [markup.goldmark.renderer]
      unsafe = true

[menu] # Menu bar under header 
[[menu.main]]
  identifier = 'About'
  name = 'About'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -120
[[menu.main]]
  identifier = 'Domestic Affairs'
  name = 'Domestic Affairs'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/domestic-affairs/'
  weight = -110
[[menu.main]]
  identifier = 'Foreign Affairs'
  name = 'Foreign Affairs'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/foreign-affairs/'
  weight = -100
[[menu.main]]
  identifier = 'Business'
  name = 'Business'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/business/'
  weight = -90
[[menu.main]]
  identifier = 'Entertainment'
  name = 'Entertainment'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/entertainment/'
  weight = -80
[[menu.main]]
  identifier = 'Medicine'
  name = 'Medicine'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/medicine/'
  weight = -70
[[menu.main]]
  identifier = 'Science and Technology'
  name = 'Science and Technology'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/science-and-technology/'
  weight = -60
[[menu.main]]
  identifier = 'Sports'
  name = 'Sports'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/sports/'
  weight = -50
[[menu.main]]
  identifier = 'Opinion'
  name = 'Opinion'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/opinion/'
  weight = -40
[[menu.main]]
  identifier = 'Parallel Universe Reports'
  name = 'Parallel Universe Reports'
  pre = "<i class='fa fa-heart'></i>"
  url = '/categories/parallel-universe-reports/'
  weight = -30